-- AlterTable
ALTER TABLE "spb" ALTER COLUMN "projectId" DROP NOT NULL;
ALTER TABLE "spb" ADD COLUMN "spbType" TEXT NOT NULL DEFAULT 'PROYEK';
ALTER TABLE "spb" ADD COLUMN "approvedByDireksi" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "spb" ADD COLUMN "approvedByDireksiAt" TIMESTAMP(3);
