-- AlterTable
ALTER TABLE "project_components" ADD COLUMN IF NOT EXISTS "dimensionL" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "dimensionP" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "dimensionT" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "markingCode" TEXT,
ADD COLUMN IF NOT EXISTS "material" TEXT,
ADD COLUMN IF NOT EXISTS "qty" DOUBLE PRECISION DEFAULT 1,
ADD COLUMN IF NOT EXISTS "unit" TEXT DEFAULT 'PCS',
ADD COLUMN IF NOT EXISTS "weight" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "qcApprovedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "qcApprovedBy" TEXT,
ADD COLUMN IF NOT EXISTS "qcNotes" TEXT;

-- AlterTable
ALTER TABLE "shipment_packages" ADD COLUMN IF NOT EXISTS "cubication" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN IF NOT EXISTS "packageType" TEXT DEFAULT 'PALET',
ADD COLUMN IF NOT EXISTS "qcApprovedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "qcApprovedBy" TEXT,
ADD COLUMN IF NOT EXISTS "qcNotes" TEXT;
