-- AlterTable
ALTER TABLE "leads" ADD COLUMN IF NOT EXISTS "estimatedTonnage" DOUBLE PRECISION DEFAULT 0;

-- AlterTable
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "estimatedTonnage" DOUBLE PRECISION DEFAULT 0;

-- AlterTable
ALTER TABLE "documents" ADD COLUMN IF NOT EXISTS "tonnage" DOUBLE PRECISION DEFAULT 0;

-- AlterTable
ALTER TABLE "boqs" ADD COLUMN IF NOT EXISTS "totalTonnage" DOUBLE PRECISION DEFAULT 0;

-- AlterTable
ALTER TABLE "boq_items" ADD COLUMN IF NOT EXISTS "weightTon" DOUBLE PRECISION DEFAULT 0;
